jobs:
- job: ${{ parameters.name }}
  displayName: TSAN
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: nightly-2018-11-18

  - script: |
        set -e
        # Make sure the benchmarks compile
        cargo build --benches --all
        export ASAN_OPTIONS="detect_odr_violation=0 detect_leaks=0"
        export TSAN_OPTIONS="suppressions=`pwd`/ci/tsan"
        export RUST_BACKTRACE=1
        # === tokio-timer ====
        # Run address sanitizer
        RUSTFLAGS="-Z sanitizer=address" \
        cargo test -p tokio-timer --test hammer --target x86_64-unknown-linux-gnu
        # Run thread sanitizer
        RUSTFLAGS="-Z sanitizer=thread" \
        cargo test -p tokio-timer --test hammer --target x86_64-unknown-linux-gnu
        # === tokio-threadpool ====
        # Run address sanitizer
        RUSTFLAGS="-Z sanitizer=address" \
        cargo test -p tokio-threadpool --tests --target x86_64-unknown-linux-gnu
        # Run thread sanitizer
        RUSTFLAGS="-Z sanitizer=thread" \
        cargo test -p tokio-threadpool --tests --target x86_64-unknown-linux-gnu
    displayName: TSAN / MSAN
    env:
      TSAN: yes

