# parameters:
#   features: []

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - ${{ each crate in parameters.crates }}:
    - ${{ each feature in crate.value }}:
      - script: cargo check -p ${{ crate.key }} --no-default-features --features ${{ feature }}
        displayName: Check `${{ crate.key }}`, features = ${{ feature }}
