jobs:
- job: ${{ parameters.name }}
  variables:
    rust_minimum_version: 1.26.0
    sanitizer_nightly_version: nightly-2018-11-18
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      platform: ${{parameters.name}}
      rust_version: stable
      rust_minimum_version: $(rust_minimum_version)

  - bash: |
      cargo test --all --no-fail-fast
      cargo test -p tokio-buf --no-default-features
      cargo doc --all
    env:
      LOOM_MAX_DURATION: 10
      CI: 'True'
    displayName: cargo test

  - bash: cargo +$(rust_minimum_version) check --all
    displayName: Minimum version support

  - bash: |
      shopt -s expand_aliases
      alias check="cargo check --no-default-features"
      check
      check --features codec
      check --features fs
      check --features io
      check --features reactor
      check --features rt-full
      check --features tcp
      check --features timer
      check --features udp
      check --features uds
    displayName: cargo check

  - bash: |
      sudo apt-get install gcc-multilib
      rustup target add $TARGET
      cargo check --all --exclude tokio-tls --target $TARGET
      cargo check --tests --all --exclude tokio-tls --target $TARGET
    condition: eq(variables['agent.os'], 'Linux')
    env: { TARGET: 'i686-unknown-linux-gnu' }
    displayName: Test cross compilation

  - bash: |
      cd tokio-async-await
      cargo +nightly check --all
      cargo +nightly check --features async-await-preview
    continueOnError: true
    displayName: Test async/await support
  
  - bash: |
      # Install the right nightly version
      rustup toolchain install $(sanitizer_nightly_version)
      # Make sure the benchmarks compile
      cargo +$(sanitizer_nightly_version) build --benches --all
      export ASAN_OPTIONS="detect_odr_violation=0 detect_leaks=0"
      export TSAN_OPTIONS="suppressions=`pwd`/ci/tsan"
      export RUST_BACKTRACE=1
      # === tokio-timer ====
      # Run address sanitizer
      RUSTFLAGS="-Z sanitizer=address" \
      cargo +$(sanitizer_nightly_version) test -p tokio-timer --test hammer --target x86_64-unknown-linux-gnu
      # Run thread sanitizer
      RUSTFLAGS="-Z sanitizer=thread" \
      cargo +$(sanitizer_nightly_version) test -p tokio-timer --test hammer --target x86_64-unknown-linux-gnu
      # === tokio-threadpool ====
      # Run address sanitizer
      RUSTFLAGS="-Z sanitizer=address" \
      cargo +$(sanitizer_nightly_version) test -p tokio-threadpool --tests --target x86_64-unknown-linux-gnu
      # Run thread sanitizer
      RUSTFLAGS="-Z sanitizer=thread" \
      cargo +$(sanitizer_nightly_version) test -p tokio-threadpool --tests --target x86_64-unknown-linux-gnu
    env: { TSAN: 'yes' }
    displayName: Run thread sanitizer checks 